### ISSUE TITLE
Doesn't compile when linked against latest puzzle-lib

### ISSUE THREAD

**Issue by sjenks** [beckbria/puzzle-web#22]
Produces the error:

C:/Code/puzzle-web/src/Braille/BrailleStream.tsx
(68,34): Property 'encoding' does not exist on type 'BrailleCharacter'. Did you mean '_encoding'?

**Comment by kfarnung** [comment]
I'll take a look at it.

**Comment by kfarnung** [comment]
Which version of puzzle-lib is being used?

**Comment by sjenks** [comment]
Yeah, that's what I meant by the linked.  Consider it more of a FYI that some change will have to be made in the next version.  So repro steps would be like:
```
cd puzzle-lib
git pull
cd ../puzzle-web
npm link ../puzzle-lib
npm start
```

**Comment by sjenks** [comment]
Scott's an idiot.

**Comment by kfarnung** [comment]
I wouldn't say that!  The GitHub fork getting stale is a common issue for people.  I find that your best bet is to either:
1. Clone the upstream repo and add your fork as a remote
```console
$ git clone https://github.com/kfarnung/puzzle-lib.git
$ cd puzzle-lib
$ git remote add sjenks https://github.com/sjenks/puzzle-lib.git
```
2. Clone your fork and add the upstream as a remote
```console
$ git clone https://github.com/sjenks/puzzle-lib.git
$ cd puzzle-lib
$ git remote add upstream https://github.com/kfarnung/puzzle-lib.git
$ git checkout master
$ git branch --set-upstream-to=upstream/master master
$ git pull
```
